### PR TITLE
chore: new domain

### PR DESCRIPTION
**Pull request by leohhhn**
## Description

This PR changes the README to include the new deployment domain following DNS changes from @jaekwon.

### CODE REVIEW

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
Why wasn't the `faucets.json` changed as well?

**Comment by leohhhn** [comment]
@zivkovicmilos 

I thought we are just changing the deployment of the Faucet Hub, not the faucet itself. What will be the new faucet URL?

**Comment by zivkovicmilos** [comment]
> @zivkovicmilos
> 
> I thought we are just changing the deployment domain of the Faucet Hub, not the faucet itself. What will be the new faucet URL?

`faucet-api.gno.land`

**Comment by leohhhn** [comment]
@zivkovicmilos 

Changed it: [cae45fc](https://github.com/gnolang/faucet-hub/pull/19/commits/cae45fccf6f623be77d04ce13434c647f76defcc)

**Review by zivkovicmilos — APPROVED** [review]
Please don't merge this yet

**Review by zivkovicmilos — APPROVED** [review]

**Pull request merged**
